name: ci
on:
  push:
    paths:
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'yarn.lock'
    branches:
      - '*'

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          workflow_id: build-docker.yml
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 30
          persist-credentials: false

      - name: Yarn install
        run: |
          yarn

      - name: Build
        run: |
          yarn build

#      - name: Test
#        run: |
#          yarn test
